name: release-preview

on:
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: github-release
          prerelease: true

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          ref: ${{ steps.release.outputs.tag_name }}

      - name: Add files and publish release
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ steps.release.outputs.tag_name }}
        run: |
            sed -i "s/__VERSION__/${TAG_NAME#v}/" fingeringdiagram.qml
            zip fingering-diagram-${TAG_NAME}.zip fingeringdiagram.qml LICENSE README.md
            gh release upload ${TAG_NAME} fingering-diagram-${TAG_NAME}.zip
